### PR TITLE
Hanna

### PR DESCRIPTION
**Pull request by Hgersten-hash**
Started working on the responsiveness of the profile page. Would love to hear feedback and discuss resolving the conflicts with others' modifications

### CODE REVIEW

**Comment by jescalada** [comment]
Looks a lot better! I think we should finish making the profile image responsive before we merge. We should also take care of aligning all the boxes.

**Review by EmilieYZhang — DISMISSED** [review]
I would suggest making the margins on the sides narrower so that there is a more efficient use of space. Good job on making the cards responsive!

**Comment by jescalada** [comment]
I'm working on the profile image right now, as well as the general margins between the cards. Trying to make sure that everything looks fine on wider screens as well.

**Review by jescalada — APPROVED** [review]
Everything looking good!

**Pull request merged**
